# Generated by Django 3.2.4 on 2021-07-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app1.Author', verbose_name='authors'),
        ),
    ]
